add_newline = false

[aws]
disabled = true

[cmd_duration]
min_time = 0
format = "[$duration](white)"

[line_break]
disabled = true

[git_status]
style = "bold white"
count = true
ahead = "[⇡${count}](bold cyan)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}(bold cyan)]"
behind = "[⇣${count}](bold cyan)"
untracked = "?${count}"
stashed = "#${count}"
modified = "[~${count}](bold yellow)"
staged = "[+${count}](bold green)"
renamed = "[»${count}(bold yellow)]"
deleted = "[✘${count}](bold red)"
conflicted = "[!${count}](bold magneta)"
